# Generated by Django 4.0.4 on 2022-06-09 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('idProduct', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de producto')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre producto')),
            ],
        ),
    ]
